version: '3'
services:
  stream_management_server:
    build:
      context: .
    deploy:
      replicas: 4
    ports:
      - "4000:4000"
  concurrent_stream_cache:
    image: redis:5.0.4-alpine
    deploy:
      replicas: 1
    ports:
      - "4001:6379"
