version: '3.5'
services:
  stream_management_server:
    build:
      context: .
    deploy:
      replicas: 4
    ports:
      - "4000:4000"
    environment:
      - EVENT_STREAM_CACHE_HOST=docker.for.mac.localhost
      - EVENT_STREAM_CACHE_PORT=4001
  concurrent_stream_cache:
    image: redis:5.0.4-alpine
    deploy:
      replicas: 1
    ports:
      - "4001:6379"
