version: '3'
services:
  redis:
    image: redis
    deploy:
      replicas: 1
    ports:
      - "4001:6379"
  stream_management_server:
    build:
      context: .
    deploy:
      replicas: 4
    ports:
      - "4000:4000"
